[project]
name = "ner-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "gliner>=0.2.29",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "motor>=3.5.0",
    "pydantic>=2.7.0",
    "pydantic-settings>=2.2.0",
    "typer>=0.12.0",
]
