[project]
name = "ner-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "gliner>=0.2.29",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "motor>=3.5.0",
    "pydantic>=2.7.0",
    "pydantic-settings>=2.2.0",
    "typer>=0.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = [
    ".notes",
    "src/playground",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true

[tool.pyrefly]
search-path = ["."]