[project]
name = "ner-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "glinker",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]

[tool.uv.sources]
glinker = { git = "https://github.com/Knowledgator/GLinker.git" }
